apiVersion: v1

siteinfo:
    description: Dockas - The online market
    title: Dockas
    keywords: startup,tech,chat
    #fb_app_id: 250528625300602
    mixpanel_key: 2376ce562fae83abb04ff50606c430fd
    #analytics_key: UA-79995910-2
    #optimizely_key: 5385733009
    #google_maps_key: AIzaSyDOko7oldevlasKPWl1x1sqZje1nzBZNvk
    base_url: //dockas.com
    logo_icon_url: //dockas.com/assets/images/logo_icon.png
    logo_favicon_url: //dockas.com/assets/images/favicon.png

isBeta: true

hostnames:
    webapp: dockas.com
    api: api.dockas.com
    socket: socket.dockas.com
    file: file.dockas.com

images:
    placeholderPath: placeholder.png

paypal:
    sandbox: "Ac95bP9cLOVq7YzUbyMNabCBWH3p1frTjzZ74a_a1DH-VFdenOtrrTD2z6qG7FLRFszgFvyu4bWh0NMa"
    production: "AdgyTk-1bkskjMaVHZeWUzIeCkEBIKr0jsOtQAXDx4rKZoaNcaU8Nq5RAHEzqj_ipfHFDVboeuNtcnyW"

mapbox:
    accessToken: pk.eyJ1IjoiYnJ1bm9zZSIsImEiOiJjaXpoOTRsd3UwMWFxMnhwbG56MTFoNnVqIn0.z8vunE1lGlbIAiW8RSNfYQ

support:
    - name: Bruno
      phone: (31)99537-0317
    - name: Marco
      phone: (37)99121-9019
    - name: Danilo
      phone: (31)99710-3611
    #- name: Felipe
    #  phone: (31)9999-9999

coupon:
    types:
        - value: percentual
          label: "%"
        - value: monetary
          label: "R$"