siteinfo:
    base_url: //dockas.dev
    logo_icon_url: //dockas.dev/assets/images/logo_icon.png
    logo_favicon_url: //dockas.dev/assets/images/favicon.png
    mixpanel_key: efd14c3ced2c622f738d1137a8592c65

#hostnames:
#    webapp: dockas.dev
#    api: api.dockas.dev
#    socket: socket.dockas.dev

hostnames:
    webapp: dockas.dev
    api: api.dockas.dev
    socket: socket.dockas.dev
    file: file.dockas.dev